# Local development overrides

url: http://localhost:4000

search                   : false
search_full_content      : false

# don't use the remote theme for local development
remote_theme: false
theme: minimal-mistakes-jekyll

analytics:
  provider: false

sass:
  style: expanded